= Prompt Engineering exercise (optional)
include::_attributes.adoc[]

NOTE: ラボのこの部分はオプションとしてマークされています。したがって、ラボの他の部分に影響を与えることなくスキップできます。時間に余裕がある場合は、ラボの最後にいつでもこの部分に戻ることができます。

IMPORTANT: ChatGPT やその他の商用サービスとやり取りする場合、望ましくない結果や仕事に適さない結果が出ないように、多くのガードレールが設けられています。ラボの演習では、これらのガードレールで保護されていないモデルを使用しており、その設定を変更します。したがって、安全な方法で実行し、得られた結果が自分や視聴者にとって適切であることを確認するのは、ユーザーの責任です。このラボの作成者は、ユーザーが得る不適切な結果について責任を負いません。

前のセクションで見たように、モデルから得られる結果に影響を与えるさまざまな要因があります。モデル パラメータ、プロンプト、クエリ、そしてもちろんデータ自体です...

これらのさまざまな要因を調整して、最良の結果を得る方法を見てみましょう。

== 設定の変更

ノートブック `03-01-nb-llm-example.ipynb` に戻り、次の変更を試してください。

- llm パラメータ (`temperature` など)。モデルをよりクリエイティブにします。
- `prompt template`。モデルの動作を変えて、詩の形で答えを出すようにします。または、エンタープライズ コンテキストでより便利なのは、さまざまなタイプの対象者 (たとえば、5 歳の子供、技術的な知識のない人、またはその逆) に話しかけているように答えを出すことです。
- `query` 自体。プロンプトの特定の側面をオーバーライドするために使用できます。これにより、ユーザー クエリを事前にフィルタリングするなど、「プロンプト インジェクション」に対するガードレールを準備することが重要である理由がわかります

== データの変更

ノートブック `03-02-summarization.ipynb` に戻り、次の変更を試してください:

- クレームを編集または新規作成して、理解しにくくします。(注: Jupyter で json ファイルを編集するには、ファイルを右クリックして [開く] > [エディター] を選択します)
- さまざまな言語を試してください

== プロンプトの変更

ノートブック `03-03-information-extraction.ipynb` に戻り、次の変更を試してください:

- クレームを編集または新規作成して、理解しにくくします
- 特定の形式を尊重するなど、日付と時刻の抽出においてモデルをより正確かつ簡潔にしてください
