FROM registry.access.redhat.com/ubi9/python-311

COPY requirements.txt /opt/app-root/src

RUN pip install -U pip && pip install -r requirements.txt

COPY model_server model_server

ENTRYPOINT ["deepsparse.server", "--task", "text-generation", "--integration", "openai", "--model_path" "zoo:llama2-7b-llama2_chat_llama2_pretrain-base_quantized
"]