
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
labels:
  opendatahub.io/dashboard: "true"
metadata:
  name: deepsparse-server
spec:
  annotations:
    prometheus.kserve.io/port: '8080'
    prometheus.kserve.io/path: "/metrics"
    openshift.io/display-name: "My deepsparse server"
  supportedModelFormats:
    - name: deepsparse
      version: "1"
      autoSelect: true
      priority: 1
  protocolVersions:
    - v1
    - v2
  containers:
    - name: kserve-container
      image: <CHANGE_ME>
      args:
        - --model_name={{.Name}}
        - --model_dir=/mnt/models
        - --http_port=8080
        - --enable_docs=True
      resources:
        requests:
          cpu: "8"
          memory: 8Gi
        limits:
          cpu: "8"
          memory: 8Gi
